import tkinter as tk
def fun():
    p = txt1.get()
    r = txt2.get()
    t = txt3.get()
    si = (float(p)*float(r)*float(t))/100
    lbl.config(text="si is "+str(si))
window = tk.Tk()
window.geometry("300x250")
window.title("Event Example")
frame = tk.Frame(master=window, width=150, height=150)
frame.pack()
lblp = tk.Label(master=frame,text="Enter P")
lblp.pack()
txt1 = tk.Entry(master=frame)
txt1.pack()
lblr = tk.Label(master=frame,text="Enter R")
lblr.pack()
txt2 = tk.Entry(master=frame)
txt2.pack()
lblt = tk.Label(master=frame,text="Enter T")
lblt.pack()
txt3 = tk.Entry(master=frame)
txt3.pack()
btn = tk.Button(master=frame,text="click",command=fun)
btn.pack()
lbl = tk.Label(master=frame)
lbl.pack()

window.mainloop()
